-- Справочники
CREATE TABLE areas (
    code INTEGER PRIMARY KEY,
    name VARCHAR(127) NOT NULL
);

CREATE TABLE schools (
    code INTEGER PRIMARY KEY,
    name VARCHAR(127) NOT NULL,
    address TEXT NOT NULL,
    area_code INTEGER NOT NULL REFERENCES areas(code)
);

CREATE TABLE ppts (
    code INTEGER PRIMARY KEY,
    school_code INTEGER NOT NULL REFERENCES schools(code),
    responsible_name VARCHAR(127) NOT NULL,
    responsible_phone VARCHAR(11) NOT NULL
);

CREATE TABLE area_responsibles (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    area_code INTEGER NOT NULL REFERENCES areas(code),
    name VARCHAR(127) NOT NULL,
    phone VARCHAR(11) NOT NULL,
    mail VARCHAR(127) NOT NULL
);

CREATE TABLE nations (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(127) NOT NULL
);

CREATE TABLE participant_statuses (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(127) NOT NULL
);

CREATE TABLE test_dates (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    day INTEGER NOT NULL,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL
);

CREATE TABLE test_attempts (
    number INTEGER PRIMARY KEY,
    name VARCHAR(127) NOT NULL
);

-- Апелляции
CREATE TABLE appeals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_date DATE NOT NULL,
    is_granted BOOLEAN NOT NULL DEFAULT FALSE,
    is_appellant_present BOOLEAN NOT NULL DEFAULT FALSE
);

-- Основные таблицы
CREATE TABLE participants (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surname VARCHAR(127) NOT NULL,
    name VARCHAR(127) NOT NULL,
    patronymic VARCHAR(127),
    birth_day INTEGER NOT NULL,
    birth_month INTEGER NOT NULL,
    birth_year INTEGER NOT NULL,
    nation_id INTEGER NOT NULL REFERENCES nations(id),
    confirmed_school_code INTEGER REFERENCES schools(code),
    is_special_category BOOLEAN NOT NULL DEFAULT FALSE,
    status_id INTEGER REFERENCES participant_statuses(id),
    next_planned_date TEXT,
    comment TEXT,
    rcoi_note TEXT
);

CREATE TABLE test_results (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id INTEGER NOT NULL REFERENCES participants(id),
    test_date_id INTEGER NOT NULL REFERENCES test_dates(id),
    is_passed BOOLEAN,
    class INTEGER NOT NULL,
    sending_school_code INTEGER NOT NULL REFERENCES schools(code),
    test_attempt_number INTEGER NOT NULL REFERENCES test_attempts(number),
    appeal_id INTEGER REFERENCES appeals(id),
    testing_center_ppt_code INTEGER NOT NULL REFERENCES ppts(code)
);
